### ISSUE TITLE
Use multiple TOCs on the same page?

### ISSUE THREAD

**Issue by lramarojaona** [ndabas/toc#11]
Hello,

I'm trying to use 2 tables of contents on the same page.

Example below:
```html
<div>
  <div class="body">
    <ol data-toc=".body" data-toc-headings="h2"></ol>
    <h2>Fuerit toto in consulatu sine provincia</h2>
    <h2>Sortietur an non</h2>
  </div>
  <div class="body">
    <ol data-toc=".body" data-toc-headings="h2"></ol>
    <h2>Phoenice Celsen ante rettulimus</h2>
    <h2>Eodem tempore Serenianus ex duce</h2>
    <h2>Et quoniam apud eos ut in capite mundi</h2>
  </div>
</div>
```

This results in 2 seperate tables of contents but both are merging all the titles together.

**Are multiple tables of contents on the same page supported by this plugin?**

Thank you!

**Comment by windmaomao** [comment]
Yeah, I have the same issue, basically, the call doesn't clean the data. So maybe manually you need to clean it before doing it again. 

```
          $("#toc").empty().toc({ content: '#write', headings: "h2, h3" });
```

**Comment by lramarojaona** [comment]
I solved this issue by adding a custom class for each body.

But your solution may also work.
