### ISSUE TITLE
Collapsible sub- list items

### ISSUE THREAD

**Issue by parasdaryanani** [ndabas/toc#13]
Would be nice to make long lists with many sub list items collapsible. Would it be okay for me to implement this and send a PR?

**Comment by ndabas** [comment]
The vision for toc is to keep it minimal; in that spirit, I am not including any code which can be replaced with other jQuery plugins or a bit of custom code. The functionality you are talking about does not fit my minimal criteria -- so no, while I will not merge that sort of code into toc, please feel free to maintain your own fork, or maybe just make a plugin for collapsible lists in general (which would work with more than just toc.)
