### ISSUE TITLE
Make toc links friendly to angularjs - add target="_self"

### ISSUE THREAD

**Issue by prasad83** [ndabas/toc#5]
Angularjs adds "/" to hash tags having # by default, adding target helps for self-referencing links on the page.

```javascript
// Add the list item
$("<li/>").appendTo(stack[0]).append(
    $("<a/>").text(elem.text()).attr("href", "#" + elem.attr("id")).attr("target", "_self")
);
</pre>

**Comment by ndabas** [comment]
`target="_self"` [is the default](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target). If another library or framework changes that behavior, you need to handle that elsewhere.

This is not an issue with the toc plugin.
