### ISSUE TITLE
Relative anchor fails when base href is set on page.

### ISSUE THREAD

**Issue by prasad83** [ndabas/toc#6]
Consider the http://site.tld/page is being viewed and <base href="http://site.tld"> is configured.

TOC link &lt;a href="#inside-page"> would result to http://site.tld#inside-page - WRONG.

Having options... base would be good. 

```javascript

$("<li/>").appendTo(stack[0]).append(
$("<a/>").text(elem.text()).attr("href", (thisOptions.base ? thisOptions.base : '') + "#" + elem.attr("id"));
);
```
In the example page stated above, I would use

```javascript
jQuery('#toc').toc({base: '/page'});
```

**Comment by ndabas** [comment]
This isn't an issue with this library, _per se_.

You can easily handle this case with some code like this:

```
jQuery("#toc").toc().find("a").attr("href", function (i, a) { return "/page" + a; });
```
