### ISSUE TITLE
Can’t reach headings from an external source

### ISSUE THREAD

**Issue by anasram** [ndabas/toc#8]
Can’t reach a heading element (the  internal anchors) from an external source.
e.g. http://somedomain.com/article.html#intro doesn’t work.

**Comment by ndabas** [comment]
It's not clear what you're talking about. If you talking about the anchors generated using the automatic ID generation feature of this library:

1. The auto-generated anchors do work, based on some quick tests with Edge, Chrome, and Firefox. For example, with this link: [https://ndabas.github.io/toc/#Automatic_ID_generation](https://ndabas.github.io/toc/#Automatic_ID_generation).
2. Even if they didn't work, that is a non-goal of this library. The only goal is to generate a TOC to show on the page; IDs are generated only as a convenience to allow clicking links in the TOC. If you are linking to headings on the page, you should probably be using IDs assigned manually (or using a build process, on the server-side, or whatever).

**Comment by anasram** [comment]
> If you talking about the anchors generated using the automatic ID generation feature of this library
Yes, that's what I mean.
> For example, with this link: https://ndabas.github.io/toc/#Automatic_ID_generation.
It works fine here!
After some tests I detected it's due to jQuery version. Your example uses jQuery v1.12.4, while I was trying to use TOC depending on jQuery v3.1.1.
Try to update jQuery in your example and will notice that it doesn't properly.
Notice that I'm still here talking about targeting an anchor from an _external_ source.

**Comment by ndabas** [comment]
Sure, I will test out the library with newer versions of jQuery, thank you for pointing that out. However, like I said, this is a non-goal of this project, so I wont be testing (or putting in a fix) for this issue specifically. Maybe I can put in some guidance in the docs about the intention and recommended usage of the automatic ID feature.
